### ISSUE TITLE
ViewDetachedFromWindow not working

### ISSUE THREAD

**Issue by ghost** [ibaozi-cn/RecyclerViewAdapter#3]
I think there is a mistake on ViewHolderExt.

```
    fun onViewDetachedFromWindow(f: ViewHolderType) {
        onViewAttached = f
    }
```

Above code is wrong, because onViewAttached not applied onViewDetachedFromWindow

It should be the following is correct.

```
    fun onViewDetachedFromWindow(f: ViewHolderType) {
        onViewDetached = f
    }
```

Please, fix it.

**Comment by ibaozi-cn** [comment]
> I think there is a mistake on ViewHolderExt.
> 
> ```
>     fun onViewDetachedFromWindow(f: ViewHolderType) {
>         onViewAttached = f
>     }
> ```
> 
> Above code is wrong, because onViewAttached not applied onViewDetachedFromWindow
> 
> It should be the following is correct.
> 
> ```
>     fun onViewDetachedFromWindow(f: ViewHolderType) {
>         onViewDetached = f
>     }
> ```
> 
> Please, fix it.

**Comment by ibaozi-cn** [comment]
Thank you. I'll fix it as soon as possible
