### ISSUE TITLE
依赖一直下不下来

### ISSUE THREAD

**Issue by GXSZone** [ibaozi-cn/RecyclerViewAdapter#6]
java如何使用

**Comment by ibaozi-cn** [comment]
该框架目前只针对kotlin写的，java还不支持

**Comment by GXSZone** [comment]
@ibaozi-cn 有没有计划支持java吗，

**Comment by ibaozi-cn** [comment]
目前封装的特性中，由于是kotlin才有的，如果换成java，就会导致整个框架变动，差不多等于重写了，应该不会考虑java封装
