### ISSUE TITLE
dev ActivityExt.kt is Error ,please check, or you can use floow code

### ISSUE THREAD

**Issue by benchegnzhou** [ibaozi-cn/RecyclerViewAdapter#7]
import android.app.Activity
import android.content.Intent

inline fun <reified T : Any> Activity.startActivity(vararg params: Pair<String, Any?>) {
    startActivity(this.intentFor<T>(*params))
}

inline fun <reified T> Activity.intentFor(vararg params: Pair<String, Any?>): Intent {
    return Intent(this,T::class.java)
}

**Comment by ibaozi-cn** [comment]
感谢🙏
